"""add staff_id to notice

Revision ID: 25067f90c79d
Revises: f0b5e41b46fd
Create Date: 2025-06-23 20:09:08.008388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25067f90c79d'
down_revision = 'f0b5e41b46fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_notice_staff_id_staff', 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notice_staff_id_staff', type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
