"""Add phone field to Message model

Revision ID: 3bc1634a973f
Revises: a5f3b1ffe588
Create Date: 2025-06-22 23:07:47.995814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc1634a973f'
down_revision = 'a5f3b1ffe588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('interest', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('interest')

    # ### end Alembic commands ###
