"""Add file_attachment to BlogPost

Revision ID: a5f3b1ffe588
Revises: efb874217912
Create Date: 2025-06-22 09:53:15.014000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f3b1ffe588'
down_revision = 'efb874217912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('file_attachment', sa.String(length=120), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('author')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('author', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('file_attachment')
        batch_op.drop_column('date_posted')
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###
