"""Add interest field to Message model

Revision ID: c126551ba21e
Revises: 25067f90c79d
Create Date: 2025-06-24 12:30:32.646100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c126551ba21e'
down_revision = '25067f90c79d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('interest')

    op.create_table('notice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('file_names', sa.TEXT(), nullable=True),
    sa.Column('image_filename', sa.VARCHAR(length=120), nullable=True),
    sa.Column('staff_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('fk_notice_staff_id_staff')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
