"""Add staff_id to BlogPost

Revision ID: efb874217912
Revises: 519519560adb
Create Date: 2025-06-22 00:04:05.794312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb874217912'
down_revision = '519519560adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_blogpost_staff_id', 'staff', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blogpost_staff_id', type_='foreignkey')
        batch_op.drop_column('staff_id')

    # ### end Alembic commands ###
