"""add image_filename to notice

Revision ID: f0b5e41b46fd
Revises: 9a9e38cf1363
Create Date: 2025-06-23 19:42:49.020710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b5e41b46fd'
down_revision = '9a9e38cf1363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notice', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
